// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BvaaJthAX4TGEu98UPB0wQmFeQg-mh8',
    appId: '1:93443611592:android:99ad613146872a10107efd',
    messagingSenderId: '93443611592',
    projectId: 'gojek-396015',
    databaseURL: 'https://gojek-396015-default-rtdb.firebaseio.com',
    storageBucket: 'gojek-396015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-UL31mv-RhdqkeQfo7hMtShZ9WrbuVg',
    appId: '1:93443611592:ios:79bf3a47689d6d90107efd',
    messagingSenderId: '93443611592',
    projectId: 'gojek-396015',
    databaseURL: 'https://gojek-396015-default-rtdb.firebaseio.com',
    storageBucket: 'gojek-396015.appspot.com',
    androidClientId: '93443611592-fjvqg7j5cga4e0ps7k1n2jhmtm34hme2.apps.googleusercontent.com',
    iosClientId: '93443611592-lvurbtrn1ki908fj19q2a86e44jirhvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGojek',
  );
}
